<!DOCTYPE html>
<html>
<head>
    <title>Fruits Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            text-align: center;
            color: #333;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
        }
        .header-info {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #007bff;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .available {
            color: green;
            font-weight: bold;
        }
        .out-of-stock {
            color: red;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #999;
            font-size: 12px;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-left: 4px solid #007bff;
        }
    </style>
</head>
<body>
    <h1>Fruit Inventory Report</h1>
    <div class="header-info">
        <p>Generated: {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Fruit Name</th>
                <th>Category</th>
                <th>Price per kg</th>
                <th>Stock Quantity</th>
                <th>Total Value</th>
                <th>Availability</th>
            </tr>
        </thead>
        <tbody>
            @foreach($fruits as $fruit)
                <tr>
                    <td>{{ $fruit->name }}</td>
                    <td>{{ $fruit->category }}</td>
                    <td>P{{ number_format($fruit->price_per_kg, 2) }}</td>
                    <td>{{ $fruit->stock_quantity }} kg</td>
                    <td>P{{ number_format($fruit->price_per_kg * $fruit->stock_quantity, 2) }}</td>
                    <td class="{{ $fruit->availability ? 'available' : 'out-of-stock' }}">
                        {{ $fruit->availability ? 'Available' : 'Out of Stock' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <p><strong>Total Products:</strong> {{ $fruits->count() }}</p>
        <p><strong>Total Inventory Value:</strong> P{{ number_format($totalValue, 2) }}</p>
    </div>

    <div class="footer">
        <p>This is an automated report generated by Fruit Sales System</p>
    </div>
</body>
</html>
